---
name: test

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  lint:
    uses: mackerelio/workflows/.github/workflows/go-lint.yml@7286c9384065633bf7d1ff6e733138deca03a764 # v1.10.0
    with:
      os-versions: '["ubuntu-latest"]'
  test:
    uses: mackerelio/workflows/.github/workflows/go-test.yml@7286c9384065633bf7d1ff6e733138deca03a764 # v1.10.0
    with:
      os-versions: '["ubuntu-latest"]'
      pre: |
        echo "GOTOOLCHAIN=auto" >> $GITHUB_ENV
